language: python
python:
  - "2.7"

before_script:
  - psql -u travis schema.sql
  - cp conf.travis.py conf.py

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: nosetests
